package com.bhp.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.bhp.greendao.bean.Mp3Media;

import com.bhp.greendao.dao.Mp3MediaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mp3MediaDaoConfig;

    private final Mp3MediaDao mp3MediaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mp3MediaDaoConfig = daoConfigMap.get(Mp3MediaDao.class).clone();
        mp3MediaDaoConfig.initIdentityScope(type);

        mp3MediaDao = new Mp3MediaDao(mp3MediaDaoConfig, this);

        registerDao(Mp3Media.class, mp3MediaDao);
    }
    
    public void clear() {
        mp3MediaDaoConfig.getIdentityScope().clear();
    }

    public Mp3MediaDao getMp3MediaDao() {
        return mp3MediaDao;
    }

}
